### ISSUE TITLE
Request for opinion on dilemma with edge cases

### ISSUE THREAD

**Issue by meeDamian** [meeDamian/country-emoji#53]
Randomly reading [release notes][emoji16] for the upcoming Emoji 16.0, I've stumbled upon the addition of the flag of Sarq (🇨🇶). Upon checking it in [the relevant standard][iso3166] it's marked as "Exceptionally reserved". Looking deeper into that matter I've found out there's more such exceptions:

| name | code | flag | `countries.json` | `ISO 3166` | has emoji | notes
|-|--:|:--:|:-:|:-:|:-:|:-:
| European Union | `EU` | 🇪🇺 | ✅ | ✅ |✅ |
| _Kosovo¹_ | `XK` | 🇽🇰 | ✅ | [❌][xk-iso] | ✅  | [Listed][xk-wiki] on wikipedia
| _United Nations¹_ | `UN` | 🇺🇳 | ❌ | ✅ | ✅ | 
| Ascension Island | `AC` | 🇦🇨 | ❌ | ✅ | ✅ |
| Clipperton Island | `CP` | 🇨🇵 | ❌ | ✅ | ✅ |
| Diego Garcia | `DG` | 🇩🇬 | ❌ | ✅ | ✅ |
| Ceuta, Melilla | `EA` | 🇪🇦 | ❌ | ✅ | ✅ |
| Canary Islands | `IC` | 🇮🇨 | ❌ | ✅ | ✅ |
| Tristan da Cunha | `TA` | 🇹🇦 | ❌ | ✅ | ✅ |
| Sarq | `CQ` | 🇨🇶 | ❌ | ✅ | ❌ | will have emoji [soon][unicode16]
| United Kingdom | `UK` | 🇺🇰 | ❌ | ✅ | ❌ |
| France, Metropolitan | `FX` | 🇫🇽 | ❌ | ✅ | ❌ |

<small>¹ - no name given in standard definition per se</small>

[emoji16]: https://emojipedia.org/emoji-16.0
[unicode16]: https://www.unicode.org/emoji/charts-16.0/emoji-released.html#1f1e8_1f1f6
[iso3166]: https://www.iso.org/obp/ui/#iso:code:3166:CQ
[xk-iso]: https://www.iso.org/obp/ui/#iso:code:3166:CQ
[xk-wiki]: https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#XK

### Any suggestions on how to deal with these?

While tha last 3 are quite obvious, should:
1. the rest be added?
2. `EU`, and `XK` be removed?
3. something else entirely be done?

cc. @BrodaNoel

**Comment by BrodaNoel** [comment]
If we have the flag-emoji, I would add them.
If we don't have the flag-emoji, I would not add them, and the we'll add them as soon as the emojis get released.

If they are not official countries, I don't care. I would add them anyways because otherwise we should have the moral conversation that we don't want to have... like... "Is Kosovo independent or is it part of Serbia?". I don't care about politics conversations and I would add them.

My rule would be: "if we have the emoji, we add them"
